version: '3.7'

services:
  cockpit:
    build:
      context: .
      dockerfile: container/Dockerfile
    volumes:
      - ./container/secrets:/container/secrets:ro
    ports:
      - "8080:8080"
      - "9091:9091"
    environment:
      - PYTHON_SERVER_HOST=python-server
      - PYTHON_SERVER_PORT=8081
    networks:
      - cockpit-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - cockpit
    networks:
      - cockpit-net

  python-server:
    build:
      context: ./container/src/py
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - cockpit-net

networks:
  cockpit-net:
    driver: bridge
