version: '3.7'

services:
  cockpit:
    build:
      context: ./container
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=production
      - PYTHON_SERVER_HOST=python-server
      - PYTHON_SERVER_PORT=8081
    networks:
      - exam-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - exam-network

networks:
  exam-network:
    driver: bridge